apiVersion: apps/v1
kind: Deployment
metadata:
  name: hate-speech-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hate-speech-ai
  template:
    metadata:
      labels:
        io.kompose.service: hate-speech-ai
    spec:
      containers:
        - image: trainingtexas/hate-speech-ai:latest
          name: hate-speech-ai
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: hate-speech-ai-pvc
          persistentVolumeClaim:
            claimName: hate-speech-ai-pvc
      restartPolicy: Always
