apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: hate-speech-ai
  name: hate-speech-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hate-speech-ai
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: hate-speech-ai
    spec:
      containers:
        - image: trainingtexas/hate-speech-ai:latest
          name: hate-speech-ai
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
