apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-service
  labels:
    app: moderator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator-service
  template:
    metadata:
      labels:
        app: moderator-service
    spec:
      containers:
        - name: moderator-service-container
          image: trainingtexas/moderator-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"  # If applicable
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "200m"
