apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderator-service
  template:
    metadata:
      labels:
        app: moderator-service
    spec:
      containers:
        - name: moderator-service
          image: trainingtexas/moderator-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: admin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://moderator-service-mysql:3306/moderator-service
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: moderator-service-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moderator-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
