apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: moderator-service
  name: moderator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: moderator-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Andrei\go\bin\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: moderator-service
    spec:
      containers:
        - image: trainingtexas/moderator-service:latest
          name: moderator-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
